apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    codefresh.io/product: my-product
  annotations:
    codefresh.io/product: my-product
spec:
  project: default
  source:
    path: resources
    repoURL: https://github.com/eti-codefresh/guestbook-local.git
    targetRevision: HEAD
  destination:
    name: arn-aws-eks-us-east-1-095585282052-cluster-daniels-dev3
    namespace: my-env
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
